THEMES = {
    "journal": {
        "label": "Journal (classique)",
        "font": "Georgia, 'Times New Roman', serif",
        "bg": "#f4f1ea",
        "card_bg": "#ffffff",
        "text": "#2b2b2b",
        "accent": "#8a1f1f",
        "muted": "#6b6b6b",
    },
    "moderne": {
        "label": "Moderne (sans-serif)",
        "font": "'Segoe UI', Helvetica, Arial, sans-serif",
        "bg": "#f5f7fa",
        "card_bg": "#ffffff",
        "text": "#1a1a1a",
        "accent": "#2563eb",
        "muted": "#6b7280",
    },
    "dark": {
        "label": "Sombre",
        "font": "'Segoe UI', Helvetica, Arial, sans-serif",
        "bg": "#121212",
        "card_bg": "#1e1e1e",
        "text": "#e5e5e5",
        "accent": "#22d3ee",
        "muted": "#9ca3af",
    },
    "nature": {
        "label": "Nature",
        "font": "'Trebuchet MS', Verdana, sans-serif",
        "bg": "#f1f8f1",
        "card_bg": "#ffffff",
        "text": "#1f2d1f",
        "accent": "#2f7d32",
        "muted": "#5a6b5a",
    },
    "pastel": {
        "label": "Pastel",
        "font": "'Poppins', 'Segoe UI', sans-serif",
        "bg": "#fdf2f8",
        "card_bg": "#ffffff",
        "text": "#3b2b3b",
        "accent": "#db2777",
        "muted": "#8a7a8a",
    },
    "mono": {
        "label": "Minimaliste mono",
        "font": "'Courier New', Courier, monospace",
        "bg": "#ffffff",
        "card_bg": "#fafafa",
        "text": "#111111",
        "accent": "#111111",
        "muted": "#555555",
    },
}